### ISSUE TITLE
frontend: Move the header to a new sidebar

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/DAPP-Trustless-Work#26]
## **Description**:

Move all current header elements (excluding the logo, light/dark mode toggle, wallet icon, and wallet button) to a new collapsible and responsive sidebar. This sidebar should be structured according to the specific sections listed below and use ShadCN's Sidebar component (reference: [Sidebar Component Documentation](https://ui.shadcn.com/docs/components/sidebar)). Ensure the sidebar adjusts based on authorization level (wallet connection - like the header works) and functions in both light and dark themes.

## **Requirements**:

1. Move all elements from the header (except logo, light/dark mode, wallet icon, and wallet button) to a new sidebar.
2. Make the sidebar collapsible, responsive, and display according to the user’s wallet authorization level.
3. Implement each section in the sidebar as follows:
   - **Section 1: Company Information**
     - Display the company name and icon (use an example from ShadCN).
   - **Section 2: Escrow (Collapsible) Like "Playground" in ShadCN Sidebar**
     - Implement as a collapsible section with the following items:
       - Initialize Escrow
       - Fund Escrow
       - Complete Escrow
       - Claim Escrow Earnings
       - Cancel Escrow
       - Refund Remaining Funds
       - Get Engagement
     - Use the icon `FaStackOverflow` from `react-icons/fa` for the main expandable option.
   - **Section 3: Documentation (Subtitle) Like "Projects" in ShadCN Sidebar**
     - Add the following items as external links:
       - **API Docs**: Link to [https://docs.trustlesswork.com/trustless-work](https://docs.trustlesswork.com/trustless-work)
       - **Website**: Link to [https://www.trustlesswork.com](https://www.trustlesswork.com)
     - Use the icon `FaExternalLinkAlt` from `react-icons/fa` for each link.
   - **Section 4: Profile**
     - Keep the profile section example from ShadCN.

## Validations:

1. Confirm that all header elements (except logo, light/dark mode, wallet icon, and wallet button) are successfully moved to the sidebar.
2. Verify that the sidebar is collapsible and adjusts responsively.
3. Test each section (Company Information, Escrow, Documentation, Profile) to ensure the layout and links work as expected.
4. Confirm that the sidebar respects authorization levels based on wallet connection.
5. Ensure proper styling and readability in both light and dark themes.
6. It should works on light / dark mode.
7. Must be fully responsive.

## Tests:

1. Test the sidebar’s collapsibility and responsiveness on various screen sizes.
2. Verify that the Escrow section can expand and collapse, and all items within it are accessible.
3. Confirm the external links under Documentation function and open correctly.
4. Check that the sidebar displays correctly based on wallet authorization status.
5. Test the sidebar’s appearance in both light and dark themes for consistency and readability.

## Recommendation:

For consistency, ensure that all icons and typography align with the overall UI style and maintain uniform padding and spacing for readability.

**Comment by raizo07** [comment]
May I be assigned to this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

Can i handle this issue?

**Comment by CollinsC1O** [comment]
Hello @JoelVR17 I would love to work on this issue and get it done

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev, and a blockchain dev kindly assign :)

**Comment by Iwueseiter** [comment]
May I pick this up?
I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga
ETA: 2 days

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. i'd love to handle this task please.

**Comment by juandiegocv27** [comment]
Could I take a shot at this?

**Comment by gadgray** [comment]
May I be assigned to this?

**Comment by Amarjeet325** [comment]
Hi , I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me?

**Comment by juandiegocv27** [comment]
> This issue is for you @juandiegocv27! 🚀 Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.
> 
> Many thanks to all the other dev's who sent in their application.

thank u sir, thanks for the opportunity

**Comment by JoelVR17** [comment]
> I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.
> 
> Can i handle this issue?

Hi @Benjtalkshow 

Would you like to take this issue?

You'll have today and tomorrow to complete it.

Please let me know soon!

**Comment by bitfalt** [comment]
Hii, my name is Daniel I'm a web3 developer and member of the Dojo Coding community. I've done frontend issues in the past and I'm familiar with using shadcn components due to university assignments and projects. I'd love to contribute to this project.

I would follow all the requirements specified in the description, ensuring the sidebar is collapsable and responsive, after my implementation I would test the new sidebar to ensure proper behaviour.

**Comment by JoelVR17** [comment]
> Hii, my name is Daniel I'm a web3 developer and member of the Dojo Coding community. I've done frontend issues in the past and I'm familiar with using shadcn components due to university assignments and projects. I'd love to contribute to this project.
> 
> I would follow all the requirements specified in the description, ensuring the sidebar is collapsable and responsive, after my implementation I would test the new sidebar to ensure proper behaviour.

There you have! 🔥

Please let me know if you have any questions or doubt.

**Comment by bitfalt** [comment]
hii @JoelVR17, unfortunately i'm unable to finish the issue on time. Kindly unassign and assign it to someone else.

**Comment by evgongora** [comment]
Hello! My name is Erick, I'm a fullstack web dev and part of Dojo Coding, I'm specializing in front-end and I this would be a great opportunity for me to contribute to this project :)

Let me know if I can hop on this.

**Comment by JoelVR17** [comment]
This issue is for you @evgongora ! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.
