### ISSUE TITLE
frontend: Create "Create Escrow" page

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/DAPP-Trustless-Work#28]
## **Description**:

Develop a button to initiate the creation of an Escrow, accompanied by a title and description. The layout should match the structure of the `Welcome` component, with a divider between the title/description and the button. When the button is clicked, it should send a `POST` request to the deployer endpoint to signal the backend to deploy the Escrow on the network. Note that the endpoint functionality is not required; simply create and implement the service as an example.

## **Requirements**:

1. Add a button labeled “Create Escrow” to the interface.
2. Include a title and description above the button, using the same structure as the `Welcome` component.
3. Insert a divider between the title/description and the button for clear visual separation.
4. Implement a `POST` request to the deployer endpoint on button click, without any parameters, as a placeholder to indicate deployment of the Escrow.
5. Develop a service for the `POST` request, even though the endpoint will not be functional.
6. For the title and description, please use Lorem Ipsum.

## **Example**:

![Image](https://github.com/user-attachments/assets/97010960-549f-4d20-a88d-97936a025148)

Just do the red part, the other part don't exist yet. (Please follow the structure of the Welcome)

## Validations:

1. Confirm that the button, title, description, and divider are displayed in the correct structure, matching the `Welcome` component’s layout.
2. Verify that clicking the button triggers a `POST` request to the deployer endpoint.
3. Ensure the structure and layout appear as intended across different screen sizes.
4. It should works on light / dark mode.
5. Must be fully responsive.

## Tests:

1. Test the button click to ensure the `POST` request is triggered to the deployer endpoint.
2. Confirm that the title, description, and divider align with the layout of the `Welcome` component.
3. Check for consistent styling and functionality across devices and themes.

## Recommendation:

Use clear naming conventions for the button and service to improve maintainability and understanding, especially for future functionality.

**Comment by Benjtalkshow** [comment]
@JoelVR17 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I will tackle the `Create Escrow` page by implementing the red section of the design, replicating the structure of the Welcome component. This includes adding a title, description, divider, and a `Create Escrow` button that triggers a placeholder POST request to the deployer endpoint. The layout will be fully responsive, working across all devices and themes, and the implementation will follow best practices to ensure maintainability and scalability.

My ETA is 48hrs.

**Comment by Ayoazeez26** [comment]
I am a software developer with over 5 years experience in building products.
Here is my onlydust profile: https://app.onlydust.com/u/Ayoazeez26

I intend to address the issue by studying and using the Welcome component as a guide. I would add the "Create Escrow" button and use a divider to separate it from the title and description. I would also implement a `POST` request to the deployer endpoint onclick of the button, to indicate deployment of the Escrow. I would also develope a service for the `POST` request even though the endpoint won't be functional at this point. I would make my solution fully responsive and ensure it works as it should on both light and dark mode.

Before submitting my PR, I would test that the `POST` request is triggered on button click, and I would also confirm that the UI aligns with the layout of the Welcome component

ETA - 48 hrs

**Comment by wheval** [comment]
Hello @JoelVR17, 

I'm Wheval a frontend developer skilled in reactjs and I also have experience working with backend endpoints. I would also test to confirm that the post request works and consistent styling across the escrow page.

I would ensure to meet all the requirements and open a draft pr so you can see my progress while at it.
Please assign, I'd be happy to do this.

ETA is 2 days max.

**Comment by Unickhub** [comment]
I'd like to handle this task.

**Comment by Michaelkingsdev** [comment]
May I handle this issue? I am an experienced frontend developer with 3 years of experience.

**Comment by Jethrolopwus** [comment]
May I try my hand at this?

**Comment by NueloSE** [comment]
Can I start working on this?

I am a frontend developer with js and js frameworks.

with the provided frame i would create reuseable commponent for the above task to enable reuse of these component in multiple pages on the the escrow page

kindly assign me the above task

**Comment by jesusre890** [comment]
Implementation Plan

General Structure:
- Title and Description:
      Sample text using Lorem Ipsum.
      Positioned at the top of the interface, similar to the layout of the Welcome 
      component.
- Divider:
       A visual separator between the title/description and the button.
- Button:
       Text: "Create Escrow".
       Triggers a POST request to the deployer endpoint when clicked.
- Visual Consistency:
       Matches the structure of the Welcome component.
       Supports light and dark modes using dynamic color variables.
- Responsiveness:
       Design adjusts seamlessly to various screen sizes.
- Button Functionality:
        Clicking the button sends a POST request to a placeholder endpoint 
         (/deployer).
        Although the endpoint is non-functional, a service will be implemented to 
         handle this request as an example.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Amarjeet325** [comment]
Can I be assigned to this?

**Comment by JoelVR17** [comment]
This issue is for you @jesusre890! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.
