### ISSUE TITLE
frontend: merge create escrow and initialize escrow with steps component

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#54]
### **Description**:  
Merge the functionalities from [Issue #28](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/28) and [Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27) into a single component. The combined feature will include a stepper where:  
1. **Step 1**: Implements the "Service Details Form" ([Issue #28](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/28)).  
2. **Step 2**: Incorporates the "Steps for Milestone Configuration" ([Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27)).  

The goal is to ensure a seamless user experience where users can move between the two steps effortlessly.  

---  

### **Requirements**:  
1. **Stepper Integration**: Use a stepper to transition between Step 1 and Step 2. The stepper should be visually clear and intuitive.  
2. **Form Design**:  
   - **Step 1**: Utilize the form design outlined in [Issue #28](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/28).  
   - **Step 2**: Follow the milestone step logic and UI specified in [Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27).  
3. **State Management**: Ensure data entered in Step 1 persists and can be accessed in Step 2.

---  

### **Validations**:  
1. Confirm the stepper allows smooth navigation between Step 1 and Step 2.  
2. Validate that the data from Step 1 (Service Details Form) is correctly captured and retained.  
3. Verify that the steps for milestone configuration function as described in [Issue #27](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/issues/27).
4. It should works on light / dark mode.
5. Must be fully responsive.

---  

### **Tests**:  
1. **Integration Testing**: Ensure the stepper integrates and transitions correctly between the steps.  
2. **State Testing**: Test data persistence between Step 1 and Step 2.  
3. **UI Testing**: Check for consistent and visually appealing design for both steps.  

---  

### **Recommendation**:  
- Use a state management library (zustand) to handle form data across steps.  
- Maintain a clean and minimal design for the stepper to avoid clutter.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by Kingsuite** [comment]
Could I take a shot at this?

**Comment by 0xdevcollins** [comment]
Can I try solving this issue?

**Comment by abdegenius** [comment]
Can I take care of this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchttps://mattedsgn.com/himebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ Can I contribute to this one?

**Comment by mimisavage** [comment]
May I handle this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 7-falseparfait** [comment]
May I take care of this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by AnoukRImola** [comment]
Hi Guys!
 I would like to work on combining the Service Details Form and Milestone Configuration into a single stepper component. Based on the project structure, this would involve:

- Creating a new stepper component that integrates ServiceDetailsForm (Step 1) and MilestoneConfiguration (Step 2)
- Using Zustand for state management between steps
- Leveraging existing shadcn/ui components and maintaining design consistency

I'll ensure the component is fully responsive and works in both light/dark modes. :)

**Comment by salazarsebas** [comment]
Hi Trustless Work,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Simplify steps by unifying steps.
- Integrate Stepper to make a nice transition.
- Follow the design standards and any doubt evacuate it with the team.
- Make sure it is fully responsive.
- Perform all the tests and send the pr waiting for feedback.

**Comment by Amarjeet325** [comment]
I am Frontend Developer specializes in creating user-facing interfaces, ensuring responsive, interactive, and visually appealing web applications.
Can I take care of this issue ??

**Comment by JoelVR17** [comment]
This issue is for you @0xdevcollins! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.

**Comment by 0xdevcollins** [comment]
> This issue is for you @0xdevcollins! 🚀 Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.
> 
> Many thanks to all the other dev's who sent in their application.

Okay sir.

**Comment by JoelVR17** [comment]
> > This issue is for you @0xdevcollins! 🚀 Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.
> > Many thanks to all the other dev's who sent in their application.
> 
> Okay sir.

Hi @0xdevcollins!

Any update?

Please, let me know!

**Comment by 0xdevcollins** [comment]
> > > This issue is for you @0xdevcollins! 🚀 Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.
> 
> > > Many thanks to all the other dev's who sent in their application.
> 
> > 
> 
> > Okay sir.
> 
> 
> 
> Hi @0xdevcollins!
> 
> 
> 
> Any update?
> 
> 
> 
> Please, let me know!

I will make a pr soon sir
