### ISSUE TITLE
frontend: create table for escrow viewer

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#56]
### **Description**:  
Design a new page featuring a table for the visualization of escrow data. Use the [shadcn Data Table](https://ui.shadcn.com/docs/components/data-table) component to structure the table. Initially, the table will not have any functionality, only display the `uid` and the following columns:  

- **Service Provider**  
- **Amount**  
- **Milestones**  

---

### **Requirements**:
1. Create a new element in the sidebar called "Escrows" with their respective path.
1. Utilize the **shadcn Data Table** component to ensure consistency with the design system.  
2. Include columns for `Service Provider`, `Amount`, and `Milestones`.  
3. Prepare the structure to allow for future functionality integration.  

---

### **Example**:  
- The table should display a mock dataset with values for `Service Provider`, `Amount`, and `Milestones`. 
- Example Row:  
  - Service Provider: `0x123...abc`  
  - Amount: `100 USDC`  
  - Milestones: `3/5 completed`  

---

### **Validations**:
- Ensure that the table renders correctly and matches the design specifications.  
- Validate that columns display the appropriate data from the mock dataset.
- It should works on light / dark mode.
- Must be fully responsive.  

---

### **Tests**:
1. Test rendering the table with sample data.  
2. Verify the correct display of columns: `Service Provider`, `Amount`, and `Milestones`.  
3. Cross-browser testing to ensure the table is responsive and visually consistent.  

---

### **Recommendation**:
- Keep the design clean and minimal, focusing on data readability.  
- Prepare comments or placeholders in the code for future functionality enhancements.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by petersdt** [comment]
Is this issue still available?

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by Jemiiah** [comment]
Hello my name is Jeremiah I'm a frontend developer in Web3. I have contributed in previous OD Hacks  i have made over 85+ contribution in past OD Hacks Here's my OD Hack profile: https://app.onlydust.com/Jemiiah.
 I have read through this issue and what this project aims to do, I understand what needs to be done. I intend to solve this issue with the following approach:
1. Adding the "Escrows" Sidebar Link
I’ll start by adding a new "Escrows" link to the sidebar. I’ll make sure it highlights dynamically when the user is on the /escrows route. To keep the structure clean, I’ll add the route to the navigation configuration file (if one exists) or update the component directly.

2. Setting Up the Escrow Page
I’ll create a new page at pages/escrows/index.tsx and use the shadcn/ui Data Table component for consistency with the design system.

3. Ensuring Light/Dark Mode Compatibility
I’ll make sure the table adapts to both light and dark modes by using the dark class from Tailwind or shadcn’s built-in theme support. I’ll test it thoroughly to ensure the contrast and readability look good.

4. Making It Fully Responsive
I’ll wrap the table in a responsive container, ensuring it scrolls horizontally on smaller screens while maintaining a readable layout.

5. Testing the Table
Once the table is set up, I’ll test it thoroughly:

i. Render it with the mock data and verify all columns display correctly.
ii. Use browser developer tools to test responsiveness on different screen sizes.
iii. Perform cross-browser checks to ensure consistent rendering in Chrome, Firefox, and Safari.

**Comment by abdegenius** [comment]
May I pick this up?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by josephchimebuka** [comment]
Hello  I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchttps://mattedsgn.com/himebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ Let me handle this issue!

**Comment by 0xdevcollins** [comment]
Could I take a shot at this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 7-falseparfait** [comment]
Can I jump on this task?

**Comment by 3th-Enjay** [comment]
May I pick this up?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
can i work on this?

**Comment by Kachimercy1** [comment]
Can I take this from here?

**Comment by diegoTech14** [comment]
Hello @JoelVR17  my name is Diego Duarte Fernández, I'm a software engineer from Costa Rica and Dojo Coding member, I have experience with technologies like JavaScript, TypeScript and React, also I'm maintainer of SafeTrust project which is a security deposit service project. 🤖

I would love to tackle this issue and contribute for your amazing project.

#### Step by step for this issue:
1. Cover all the requirements: I will ensure that all the requirements are covered

2. Implementing test data: I will implement test data into the table to ensure that anything is okay and the info is displaying good.

3. Validating the table to ensure that the table works with dark mode, responsive design and display the appropriate mock up data

4. Design: For this issue I will ensure that the table design matches with the entire web and minimalist design.

Thanks for your consideration.

Best regards, Diego Duarte Fernández. ✨

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


Add a new "Escrows" element to the sidebar with its corresponding path. The table should include columns for Service Provider, Amount, and Milestones, and display mock data such as Service Provider: 0x123...abc, Amount: 100 USDC, Milestones: 3/5 completed. Ensure the table is responsive, visually consistent with the design system, and supports both light and dark modes. Validate proper rendering and display of data, performing tests for responsiveness, cross-browser compatibility, and correct column mapping. Include clear comments or placeholders for future functionality, maintaining a clean and minimal design for optimal readability.

**Comment by KevinLatino** [comment]
Hi, I’d like to work on this issue. I’ll create an "Escrows" page with a table using the shadcn Data Table component to display Service Provider, Amount, and Milestones. The table will be responsive, support light/dark mode, and include a mock dataset. I’ll add the "Escrows" link to the sidebar and prepare the structure for future functionality.

**Comment by KevinLatino** [comment]
Hello My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

For this issue  I’ll create an "Escrows" page with a table using the shadcn Data Table component to display Service Provider, Amount, and Milestones. The table will be responsive, support light/dark mode, and include a mock dataset. I’ll add the "Escrows" link to the sidebar and prepare the structure for future functionality.

**Comment by Amarjeet325** [comment]
I am Frontend Developer specializes in creating user-facing interfaces, ensuring responsive, interactive, and visually appealing web applications.
Can I take care of this issue ??

**Comment by JoelVR17** [comment]
This issue is for you @KevinLatino! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.
