### ISSUE TITLE
frontend: implement tooltip in all form fields

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#57]
### **Description**:  
Integrate tooltips using the [shadcn tooltip](https://ui.shadcn.com/docs/components/tooltip) component in all fields of each form to provide users with information about each entity or attribute.  

- Include an icon:  
  ```javascript
  import { CiCircleInfo } from "react-icons/ci";
  ```
  Place this icon in left side of the form field

- Tooltips must explain the purpose of each field in a clear and concise manner.  

---

### **Fields and Descriptions**:
- **Client**: The name or identifier of the client.  
- **Service Provider**: The address of the entity receiving the payment.  
- **Platform Address**: The platform's wallet address or identifier.  
- **Amount**: The amount agreed upon (price of product/service).  
- **Release Signer**: The party responsible for releasing funds.  
- **Milestones**: Specific goals or phases linked to the contract.  
- **Contract ID**: The unique identifier of the contract.  
- **Engagement**: The unique identifier linking this escrow to a specific project or transaction.
- **Dispute Resolver**: Entity responsible for resolving disputes fairly between parties.
- **Platform Fee**: A service charge applied to transactions on the platform.

---

### **Requirements**:
1. Use the **shadcn tooltip** component for consistency.  
2. Ensure tooltips are accessible and responsive.  
3. Add meaningful descriptions for each field to enhance user understanding.  
4. Ensure tooltips do not obstruct user interactions.  

---

### **Example**:  
- A tooltip appears when the user hovers over the information icon or label for a form field.  
- Example: Hovering over the "Amount" field displays: *"The amount agreed upon (price of product/service)."*  

---

### **Validations**:
- Verify that all tooltips display the correct information for each field.  
- Test accessibility and responsiveness.  
- Ensure tooltips are styled consistently with the design system.  
- It should works on light / dark mode.
- Must be fully responsive.

---

### **Tests**:
1. Unit tests to confirm tooltips appear with the correct content.  
2. Test interactions to ensure tooltips do not interfere with form inputs.  
3. Cross-browser testing for tooltip functionality.  

---

### **Recommendation**:
- Use concise, user-friendly language for tooltips.  
- Test tooltips with end-users for feedback.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by abdegenius** [comment]
I'd be happy to do this.

**Comment by raizo07** [comment]
Can I tackle this one? I'm a Software developer with over 3 years experience

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by mimisavage** [comment]
I'd love to give this a go.

**Comment by Kingsuite** [comment]
Can I be assigned to this?

**Comment by chibokaxavier** [comment]
Hi im Xavy, a fullstack web developer , and here is how i plan to go about the issue  I’d add tooltips to all form fields using the Shadcn tooltip component, placing an info icon (CiCireInfo) to the left of each field. The tooltips would provide clear, concise explanations for each field, like describing "Amount" as "The agreed price for the product or service."They’d be styled to match the design, work in light and dark modes, and be fully responsive. I’d test them to ensure they show the correct information, don’t obstruct form use, and enhance the user experience by making the form more intuitive.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will integrate tooltips using the shadcn tooltip component for all form fields, providing concise explanations for each field. The tooltips will be triggered by an icon CiCircleInfo, placed on the left side of each form field. The tooltips will be accessible, responsive, and styled according to the design system, ensuring they do not obstruct user interactions. I will ensure compatibility with both light and dark modes, and conduct tests for correct content, accessibility, and responsiveness.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by therealemino** [comment]
May I handle this issue?

**Comment by pablomadrigal** [comment]
## I'm Pablo Madrigal.
I'm a Fullstack Developer with more than 5 years of experience primary on React and Node.js and now learning web3, I'm also part of Dojo Coding ⛩️

## Problem
Implement Tooltip for All Form Fields

## Solution
Im going to add tooltips using the [shadcn tooltip](https://ui.shadcn.com/docs/components/tooltip "shadcn tooltip") component to each form entry and add the icon `CiCircleInfo` in the left side of the following form fields
- Client
- Service Provider
- Platform Address
- Amount:
- Release Signer
- Milestones
- Contract ID
- Engagement
- Dispute Resolver
- Platform Fee

### Steps
#### 1. Add the corresponding tooltips on the form field
Modify the file `src/components/ui/form.tsx` to include a no required prop with the description that is going to be on the tooltip so if the prop is present it would render the tooltip

#### 3. Add unit test
Add unit test for sort functionality

**Comment by Amarjeet325** [comment]
I am  Frontend Developer specializes in creating user-facing interfaces, ensuring responsive, interactive, and visually appealing web applications. 
Can I take care of this issue ??

**Comment by ShantelPeters** [comment]
Let me try this one!

**Comment by Villarley** [comment]
hi @JoelVR17,
I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.
I’ll add tooltips to all form fields using the shadcn tooltip component and place the CiCircleInfo icon on the left side of each field. Tooltips will include clear, concise descriptions like “Amount: The agreed-upon price for the product/service.” They’ll be fully responsive, accessible, and styled to match light/dark mode. I’ll also test to ensure tooltips don’t interfere with form interactions and work smoothly across devices.

ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by Nityam573** [comment]
Can I take this issue?

**Comment by OWK50GA** [comment]
Can I attempt this issue?

**Comment by mymiracle0118** [comment]
Could I take over this issue?

**Comment by emmanueldindu** [comment]
May I take care of this?

**Comment by zkCaleb-dev** [comment]
This issue is for you @Benjtalkshow ! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.
