### ISSUE TITLE
frontend: breadcrumb in header

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#58]
### **Description**:  
Modify the existing breadcrumb in the header to dynamically generate the breadcrumb based on the current route. The breadcrumb should update according to the user's navigation path and each part of the breadcrumb should be clickable, allowing users to navigate back to previous pages. The modifications should be made in the `Header.tsx` file located in `src/components/header/`.

---

### **Requirements**:  
1. **Dynamic Breadcrumb**: The breadcrumb should be generated dynamically based on the route structure. It should change depending on where the user is in the application.  
2. **Clickable Breadcrumbs**: Each segment of the breadcrumb should be a clickable link that allows the user to go back to that page.  
3. **Modify `Header.tsx`**: Update the existing breadcrumb functionality in `src/components/header/Header.tsx` to handle this dynamic behavior.  
4. **Route-based Generation**: Use the current route to generate the breadcrumb. For example, if the user is on `/projects/123`, the breadcrumb should be `Home > Projects > 123`.  
5. **Responsive Design**: Ensure the breadcrumb adapts to different screen sizes without breaking the layout.

---

### **Validations**:  
1. Ensure the breadcrumb updates correctly when navigating between different routes.  
2. Validate that each breadcrumb part is clickable and redirects to the correct page.  
3. Check that the breadcrumb adapts to different screen sizes and works as expected on mobile devices.  
4. It should works on light / dark mode.
5. Must be fully responsive.

---

### **Tests**:  
1. **Navigation Testing**: Test the breadcrumb links to ensure they correctly navigate to the associated pages.  
2. **Responsiveness Testing**: Verify that the breadcrumb layout adjusts to various screen sizes.  
3. **Route Testing**: Ensure that the breadcrumb dynamically changes according to the route.

---

### **Recommendation**:  
- Use the `useRouter` hook from Next.js to access the current route and generate the breadcrumb.  
- Make use of conditional rendering to handle different route structures.  
- Ensure that the breadcrumb's design matches the rest of the header and doesn't interfere with other components.

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by NowGoody** [comment]
I’m interested in this one.

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by abdegenius** [comment]
Could I be assigned to this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by wugalde19** [comment]
Hi team,
I’m William from Costa Rica 🇨🇷 and a member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as a Full-Stack engineer in several technologies including the ones used on this project Typescript mostly on web3 projects that I’ve contributed in both Hackathons and OD Hacks

Profiles:
https://app.onlydust.com/u/wugalde19
https://github.com/wugalde19

The way I'd approach this is by creating a generic component called breadcrumbs that I can either build from scratch or use as a wrapper of another js library like https://www.npmjs.com/package/use-react-router-breadcrumbs.
In any case I'll make sure that it works route-based, I'll share many designs so that you can choose the one you like the most and looks better in light and dark mode

**Comment by Benjtalkshow** [comment]
May I pick this up?

**Comment by austineblaise** [comment]
I'm a frontend JavaScript/TypeScript Blockchain developer. I’ll modify the breadcrumb in the header to dynamically generate based on the current route. Each part will be clickable, allowing users to navigate back to previous pages. I'll ensure it’s responsive, works on both light and dark modes, and adapts to different screen sizes. Looking forward to improving the navigation experience!

**Comment by 3th-Enjay** [comment]
I’d like to help with this.

**Comment by blessingbytes** [comment]
Can I handle this task?

**Comment by ussyalfaks** [comment]
I would love to work on this. My name is Usman, and I have solid experience in JavaScript, TypeScript, and React. I'm confident I can contribute effectively to this task.

**Comment by Kachimercy1** [comment]
Can I tackle this one?

**Comment by therealemino** [comment]
I’d like to help with this.

**Comment by Amarjeet325** [comment]
A Frontend Developer specializes in creating user-facing interfaces, ensuring responsive, interactive, and visually appealing web applications. Can I take care of this issue ??

**Comment by ShantelPeters** [comment]
May I take this issue on?

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

Additionally, I’m a Gold Contributor with over 15 merged PRs, showcasing my commitment to open-source development and collaborative problem-solving.

To tackle this issue:
I’ll update the Header.tsx to include a dynamic breadcrumb that generates based on the current route using Next.js useRouter. Each breadcrumb part will be clickable, allowing easy navigation to previous pages. I’ll ensure the breadcrumb is responsive, styled consistently, and works in light/dark mode across all screen sizes.

ETA: 12-48 hours. Feel free to reach out via Telegram

**Comment by davedumto** [comment]
Hi, my name is David, and I am skilled in JavaScript, TypeScript, Tailwind CSS, and ShadCN.
To address this issue, I plan to dynamically generate breadcrumbs based on the current route using React Router's useLocation, ensuring each segment is clickable and styled responsively with Tailwind CSS. I will also implement fallback handling for edge cases, such as invalid or deeply nested routes. ETA: 3 days.

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

I’d begin by reviewing how the breadcrumb currently works in the Header.tsx file. Then, I’d use Next.js’s useRouter hook to get the current route and dynamically create the breadcrumb based on the URL. Each part of the breadcrumb will be a clickable link so users can navigate back to previous pages. I’d also make sure the breadcrumb design blends with the rest of the header and works well in both light and dark mode. Afterward, I’d test it to ensure it’s responsive on different screen sizes. Finally, I’d check that all breadcrumb links are clickable, take users to the right pages, and update properly as the user navigates.

**Comment by pablomadrigal** [comment]
## I'm Pablo Madrigal.
I'm a Fullstack Developer with more than 5 years of experience primary on React and Node.js and now learning web3, I'm also part of Dojo Coding ⛩️

## Problem
Dynamic breadcrumb in header

## Solution
Using the `usePathname` hook from Next.js I'm going to get the url path a create the dynamic breadcrumb on the file `src/components/header/Header.tsx` and make every part clickeable so we can navigate with it.

## Unit test
Create the unit test for the dynamic breadcrumb

**Comment by mymiracle0118** [comment]
Can I work on this, please?

**Comment by emmanueldindu** [comment]
I'd like to take this issue.
