### ISSUE TITLE
frontend: create page for dashboard

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#59]
### **Description**:  
Create a set of reusable components for the dashboard page. These components should follow the design and functionality structure similar to the [Shadcn Dashboard Example](https://ui.shadcn.com/examples/dashboard). The components should be placeholders for future data and can be easily integrated with real data once the backend functionalities are implemented. 

---

### **Requirements**:  
1. **Dashboard Layout**: Implement a responsive layout with sections for key metrics and data visualization.
2. **Reusable Components**: Create modular components that can be reused across different sections of the dashboard, such as:
   - **Card**: Display key metrics like Total Users, Revenue, etc.
   - **Charts**: Placeholder components for charts such as line charts, bar charts, etc.
   - **Table**: A table to display a list of recent activities or transactions.
   - **Progress Bars**: Show progress for tasks, payments, etc.
   - **Sidebar**: A sidebar to navigate between different sections of the dashboard.
3. **Styling**: Ensure that the components are styled similarly to the Shadcn dashboard, with a clean and professional look.
4. **Responsive Design**: Make sure that the dashboard components are responsive and adapt well to different screen sizes.
5. **Icons**: Use appropriate icons for buttons, actions, and indicators (e.g., from [react-icons](https://react-icons.github.io/react-icons/)).
6. **Placeholder Data**: Use dummy data for now, with future integrations to replace them once the backend is ready.

---

### **Validations**:  
1. Ensure that each component (Card, Chart, Table, Progress Bar, Sidebar) is reusable and modular.
2. Validate that the layout adjusts properly to different screen sizes.
3. Confirm that the placeholder data is displayed correctly for each component.
4. Ensure the navigation sidebar allows switching between different sections.
4. It should works on light / dark mode.
5. Must be fully responsive.

---

### **Tests**:  
1. **Component Rendering**: Verify that each component (Card, Chart, Table, etc.) renders correctly.
2. **Responsiveness Testing**: Check that the layout and components adapt to different screen sizes (mobile, tablet, desktop).
3. **UI Testing**: Ensure that all UI elements (icons, buttons, charts) are properly styled and aligned.

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by Kingsuite** [comment]
Can I take care of this issue?

**Comment by 0xdevcollins** [comment]
Can I be assigned to this?

**Comment by DanielEmmanuel1** [comment]
I’d love to work on this task.

I will review the Figma design and assess dependencies with issue. Using Next.js with TypeScript, I’ll create a dedicated folder structure for the dashboard page and its components, ensuring its reusability.

I'll use Tailwind CSS for responsive styling, incorporating media queries and flex/grid systems to make the layout adaptable to all screen sizes. Finally, I’ll test the design across various devices and browsers to confirm responsiveness and consistency.

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by abdegenius** [comment]
Can I take this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by caxtonacollins** [comment]
Is it okay if I tackle this? this will be my first time contributing. I am ready to put in the work

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by chibokaxavier** [comment]
Hey! I’m Xavier, a software developer who specializes  in full-stack development. I excel at bringing designs to life with clean, responsive code and also i ensure i build seamless functional systems to go with the design, here is how i plan on taclkling this issue , I’d build a responsive dashboard with reusable components inspired by the Shadcn Dashboard. Using   Tailwind, I’d create  components like cards, charts, tables, progress bars, and a sidebar, all designed to work with placeholder data for now and easily integrate real data later.
The layout would be fully responsive, tested across screen sizes, and support light/dark mode using a  custom useTheme hook that comes iwth tailwind. I’d ensure the components are flexible, styled consistently, and validated for proper rendering, navigation, and UI alignment. This approach ensures the dashboard is scalable, user-friendly, and ready for future backend integration.

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi (@deeseeker), a frontend developer with over two years of experience in React, TypeScript, and JavaScript. I am currently working on a social media app for African creators (https://app.myrevva.com/).

I have reviewed the requirements carefully and will convert the designs with great attention to detail. You can check out my portfolio for a sample of my work that fits this requirement, such as Logisfi(https://logisfi-pro-app.vercel.app/), available on my GitHub.

I would love the opportunity to take on this issue.

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, I have been contributing to this project and would like to keep doing so I would like to contribute to this issue!

I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 

I’d build a dashboard with a clean, responsive layout. It would have sections for key info like metrics and charts. I’d make reusable parts like cards for stats, charts, tables, progress bars, and a sidebar for navigation. Everything would match the Shadcn dashboard style and work on all screen sizes. For now, I’d use dummy data :)

**Comment by Benjtalkshow** [comment]
Hello @mo-jaber 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 7-falseparfait** [comment]
Mind if I take this issue?

I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, and JavaScript. I have experience in creating responsive layouts and reusable components while ensuring consistency with design guidelines. I would love to work on this issue, building the dashboard page with modular, responsive components, adhering to the Shadcn dashboard style, and preparing it for seamless backend integration.

**Comment by ONEONUORA** [comment]
Could I take a shot at this? I am a full stack and blockchain developer. ETA 24 hours

**Comment by 3th-Enjay** [comment]
Can I start working on this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
I have solid experience in both web2 and web3 and have contributed to open-source projects that ended up being merged both on web2 and web3
will be glad to work on this as my first contribution to this project
I will make sure to implement a pixel perfect UI with reference to the Figma design above

**Comment by kimcascante** [comment]
I'm Kimberly Cascante, a proud member of Dojo Coding! ⛩️
I have previously worked with TypeScript, including implementing conditional logic to disable buttons based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the code, then proceed to create reusable component s following the project's structure. I'll ensure proper validations, test the solution, and prepare a PR for review.
I value clear communication and constructive feedback, as I believe they are key to collaborative success.
Happy to contribute!

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Luluameh** [comment]
I’d love to work on this task.

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub,
- I will write the code to create different reusable components that will be used in the Dashboard Page in the `/src/app/dashboard/page.tsx` file.
- I will maintain the brand color theme and project structure
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices
- I will test and make sure everything works accordingly before committing and make PR

## ETA
24 Hours

**Comment by Amarjeet325** [comment]
I am MERN Stack Developer specializes in building full-stack web applications using MongoDB, Express.js, React.js, and Node.js, covering both frontend and backend development. They excel in creating dynamic, scalable, and efficient web solutions.Can I take this issue?

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world.
### How would I approach this issue?
First, I'll start by analizing how are current components structured to make sure the new ones stay consistent with the already implemented patterns.
After that I'll start creating the smallest dynamic/reusable components that I would need (cards, tables, bars, etc). Once all this smaller components are implemented, I'll continue with the dashboard integration as its own component ensuring that both the atomic components and the page remain responsive on all devices and screen types.

**Comment by stephanniegb** [comment]
I’d love to work on this task. I have 3 years of experience build beautiful, accessible and performant user interfaces and i would do a great job tackling this issue.
- i would each component is reusable and modular
- make sure that the pages are full responsive and look great on every screen size 
- confirm that the placeholder data is displayed properly and also mack sure to account for edge cases
- Ensure the navigation sidebar allows smooth switching between different sections.
- makes sure that it works with the light/dark mode.
- i would ensure that i test properly

Here are some of my recent projects for your reference:                                                                                                - https://tba-frontend-eta.vercel.app 
- https://scroll-transform-recreate.vercel.app
- https://three-js-galaxy-silk.vercel.app/

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will make it responsive and similar to the shadcn ui dashboard, i will make it dark or light mode, also creating resuable modular and the sidebar switching between different sections.

**Comment by ShantelPeters** [comment]
Is this issue still available?

**Comment by Jagadeeshftw** [comment]
Hi @armandocodecr  ,

I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems.

My approach:

To tackle this issue, I’ll create reusable and modular components like Cards, Charts, and Tables, styled as per the Shadcn Dashboard Example.
I’ll implement a responsive layout with placeholder data for future backend integration.
Lastly, I’ll test all components for responsiveness, light/dark modes, and clean rendering.

If it is assigned to me then, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by armandocodecr** [comment]
This issue is for you @Jemiiah ! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application. 🔥
