### ISSUE TITLE
full stack: create settings page

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#60]
### **Description**:  
Develop a settings page with two main sections:  
1. **Theme Toggle**: A switch to toggle between light and dark mode.  
2. **Preferences**: A checkbox to allow the user to indicate whether to save escrows or not.  
3. **Profile**: Keep the same UI of the profile from the example.

---

### IMPORTANT

Theme Toggle should be saved in a **persistent state** using [Zustand](https://docs.pmnd.rs/zustand/getting-started/introduction). -> Make sure it is the same toggle as the shadcn toggle.

Profile and Preferences must be saved in Firebase. In "users" collection.

---

### Firebase

In the issue request, **your email address must be included**, otherwise it will be discarded. This is so we can give you access to firebase

Enter the following link: https://console.firebase.google.com/u/0/project/trustless-work/overview

---

### **Example of 'How to insert data in firebase'**
[Check this example branch](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/tree/example/how-to-integrate-firebase)

---

### **Requirements**:  
1. **Page Layout**: Create a clean and organized layout for the settings page with two sections:
   - **Theme Toggle**: Include a switch to toggle light/dark mode.
   - **Preferences**: Include a labeled checkbox for "Save Escrows".
   - **Profile**: Include "identification, name, lastName, saveEscrow and wallet (Wallet won't appear in the form, it'll be saved automatically)"
3. **Reusable Components**: Follow the [Shadcn Form Example](https://ui.shadcn.com/examples/forms) for consistent styling and functionality.  
4. **Code Standards**: Ensure the implementation follows clean code practices, modularity, and includes clear documentation.

---

### **Example**:  

- **Theme Section**:  
![Image](https://github.com/user-attachments/assets/125e9a60-7b0c-4310-917d-a5f9cee01ff2)

- **Preferences Section**:  
![Image](https://github.com/user-attachments/assets/b3e19da1-dde4-4cc8-b4e3-919bbe0996bc)

- **Profile**:
![Image](https://github.com/user-attachments/assets/612a1a72-40aa-4261-9793-9c1b358d2db1)

---

### **Validations**:  
1. Ensure the theme toggle correctly switches between light and dark modes.  
2. Validate that the "Save Escrows" checkbox accurately updates the Zustand state.  
3. Confirm that the state persists across sessions.
4. It should works on light / dark mode.
5. Must be fully responsive.

---

### **Tests**:  
1. **State Testing**: Validate that the Zustand state updates correctly when toggling the switch or checkbox.  
2. **Persistence Testing**: Verify that preferences persist after a page refresh.  
3. **UI Testing**: Ensure proper styling and layout for all components.  

---

### **Recommendation**:  
- Use Zustand's `createJSONStorage` or similar to persist the state.  
- Follow best practices for Zustand implementation, including modular stores and state management.  
- Match the design and UX to the [Shadcn Forms Example](https://ui.shadcn.com/examples/forms) for consistency.

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by petersdt** [comment]
May I take care of this?

**Comment by 0xdevcollins** [comment]
Can I work on this, please?

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

Proposed Approach:  


ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by abdegenius** [comment]
Can I tackle this one?

**Comment by raizo07** [comment]
Could I take on this issue? I'm a Software developer with over 3 years experience

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by tamaraantonella** [comment]
I'd like to take this issue.

**Comment by jesusre890** [comment]
Page Layout:

Two main sections: "Theme Toggle" and "Preferences".
Follow Shadcn form example for consistent styling and layout.
Use reusable components to maintain modularity and consistency.

Theme Toggle:

Implement a toggle for light/dark mode using Zustand with persistent state (createJSONStorage).
Ensure it matches the Shadcn toggle styling and functionality.
Validate the state updates and persists across sessions.

Preferences:

Add a labeled checkbox for "Save Escrows".
Save this preference in the users collection in Firebase along with profile data.

Profile Section:

Keep the existing UI for profile, including fields for:
Identification, name, lastName, saveEscrow, and wallet (wallet saved automatically).

Firebase Integration:

Save preferences and profile updates to the users collection in Firebase.
Use the provided example branch for guidance.

**Comment by zintarh** [comment]
I’m interested in this one.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ONEONUORA** [comment]
Can I contribute to this one? I am a full stack and blockchain developer. ETA 24 hours

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Kachimercy1** [comment]
Can I work on this, please?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by Amarjeet325** [comment]
I am MERN Stack Developer specializes in building full-stack web applications using MongoDB, Express.js, React.js, and Node.js, covering both frontend and backend development. They excel in creating dynamic, scalable, and efficient web solutions.Can I take this issue?

**Comment by JoelVR17** [comment]
This issue is for you @jesusre890! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.
