### ISSUE TITLE
full stack: create page for request an API key

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#61]
### **Description**:  
Develop a new page titled **"Request an API Key"**, accessible via:  
1. A link in the **sidebar**.  
2. A link/button on the homepage (`/`), near the **Connect/Disconnect** button.

This page will allow users to request an API key without requiring wallet connection.  

The form should include the following fields:  
- `Name`  
- `Last Name`  
- `Email`  
- `Type` (dropdown with `Company` or `Individual`)  
- `Description`  

---

### Firebase

In the issue request, **your email address must be included**, otherwise it will be discarded. This is so we can give you access to firebase

Enter the following link: https://console.firebase.google.com/u/0/project/trustless-work/overview

---

### **Example of 'How to insert data in firebase'**
[Check this example branch](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/tree/example/how-to-integrate-firebase)

---

### **Requirements**:  
1. **Form Creation**:  
   - Build a form with the specified fields and proper UI validation for each input.  
   - Ensure all fields are required.  

2. **Firebase Integration**:  
   - Store the form data in the **`api keys` collection** in Firebase.  
   - Validate the email field to ensure it is **unique** in the collection. Only one API key request per email should be allowed.

3. **Validation**:  
   - Check if the email already exists in the `api keys` collection. If it does, display an error message:  
     _"An API key has already been requested with this email."_  

4. **Navigation**:  
   - Add a link to this page in the **sidebar**.  
   - Add a link/button to this page on the homepage (`/`), near the **Connect/Disconnect** button.  

5. **UI Standards**:  
   - Follow consistent design standards, matching the existing styling and layout of the application.  

---

### **Validations**:  
1. Ensure form validation for all required fields.  
2. Confirm the email is unique in the `api keys` collection.  
3. Validate correct Firebase insertion on successful form submission. 
4. It should works on light / dark mode.
5. Must be fully responsive. 

---

### **Tests**:  
1. **Form Validation**: Ensure all fields are required and display appropriate error messages when invalid.  
2. **Email Validation**: Test cases for emails already in the collection and ensure no duplicates are allowed.  
3. **Firebase Integration**: Verify data is correctly stored in the `api keys` collection after submission.  
4. **UI Navigation**: Confirm links in the sidebar and homepage (`/`) navigate to the new page.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by 0xdevcollins** [comment]
Could I be assigned to this?

**Comment by abdegenius** [comment]
Can I tackle this one?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Ekene001** [comment]
Please can i be assigned to this task? I'm a frontend and blockchain developer and This is my first time contributing to this repository.

ETA: 2days

**Comment by ONEONUORA** [comment]
Let me handle this issue! I am a full stack and blockchain developer. ETA 24 hours

**Comment by blessingbytes** [comment]
I would love to tackle this issue

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Kachimercy1** [comment]
Could I take on this issue?

**Comment by respp** [comment]
Hello! I am Renzo Barcos, member of the Dojo community and am excited about the opportunity to make my first contributions to Trustless. For more, my website: www.renzobarcos.site

My plan is:

1. Form Creation:

- Create a new page titled with the required form.
- Ensure all fields are mandatory and implement appropriate UI validations for each field.
- Implement email field validation, ensuring the email is unique within the api_keys collection in Firebase. Display an error message if the email already exists.
2. Firebase Integration:

- Integrate Firebase to store form data in the api_keys collection.
- Before inserting the data, check if the email already exists to avoid duplicates in API key requests.
- Use Firebase Firestore for efficient data insertion.
3. Navigation:

- Add links in the sidebar and on the homepage to redirect users to the new API key request page.
4. Design and Responsiveness:

- Ensure the page follows the existing design standards of the application for visual consistency.
- Implement support for both light and dark modes using the established design system.
5. Validations and Testing:

- Verify that all form fields are validated correctly before submission.
- Test to ensure duplicate emails are identified, and that multiple requests with the same email are not allowed.
- Validate that the data is correctly inserted into Firebase and that email validation works properly.
- Ensure that the sidebar and homepage links correctly redirect to the new page.
6. Additional Testing:

- Perform tests to ensure all required fields display appropriate error messages when invalid.
- Validate the Firebase integration to ensure data is stored correctly.
- Test navigation to ensure a smooth and optimal user experience.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by tamaraantonella** [comment]
Can I take this issue?

**Comment by Amarjeet325** [comment]
I am  MERN Stack Developer specializes in building full-stack web applications using MongoDB, Express.js, React.js, and Node.js, covering both frontend and backend development. They excel in creating dynamic, scalable, and efficient web solutions.Can I take this issue?

**Comment by ShantelPeters** [comment]
I’d love to work on this task.

**Comment by armandocodecr** [comment]
This issue is for you @respp ! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application. 🔥
