### ISSUE TITLE
full stack: create page for report issues

### ISSUE THREAD

**Issue by JoelVR17** [Tico4Chain-Coders/dApp-Trustless-Work#62]
### **Description**:  
Develop a new page titled **"Report an API Issue"**, accessible via:  
1. A link in the **sidebar**.  
2. A link/button on the homepage (`/`), near the **Connect/Disconnect** button.

This page will allow users to report issues or make recommendations for the Trustless API without requiring wallet connection.  

The form should include the following fields:  
- `Name`  
- `Last Name`  
- `Email`  
- `Type` (dropdown with `Bug` or `Recommendation`)  
- `Description`  

---

### Firebase

In the issue request, **your email address must be included**, otherwise it will be discarded. This is so we can give you access to firebase

Enter the following link: https://console.firebase.google.com/u/0/project/trustless-work/overview

---

### **Example of 'How to insert data in firebase'**
[Check this example branch](https://github.com/Tico4Chain-Coders/dApp-Trustless-Work/tree/example/how-to-integrate-firebase)

---

### **Requirements**:  
1. **Form Creation**:  
   - Build a form with the specified fields and proper UI validation for each input.  
   - Ensure all fields are required.  

2. **Firebase Integration**:  
   - Store the form data in the **`api issues` collection** in Firebase.  
   - No duplicate validation is needed for this feature, allowing multiple submissions from the same user/email.

3. **Navigation**:  
   - Add a link to this page in the **sidebar**.  
   - Add a link/button to this page on the homepage (`/`), near the **Connect/Disconnect** button.  

4. **UI Standards**:  
   - Follow consistent design standards, matching the existing styling and layout of the application.  

---

### **Validations**:  
1. Ensure form validation for all required fields.  
2. Validate correct Firebase insertion on successful form submission.
3. It should works on light / dark mode.
4. Must be fully responsive. 

---

### **Tests**:  
1. **Form Validation**: Ensure all fields are required and display appropriate error messages when invalid.  
2. **Firebase Integration**: Verify data is correctly stored in the `api issues` collection after submission.  
3. **UI Navigation**: Confirm links in the sidebar and homepage (`/`) navigate to the new page.  

⚠️ **Please follow the guidelines for requesting an issue, launching commits, and describing PRs. Otherwise, they will be ignored.** ⚠️

**Comment by Kingsuite** [comment]
May I take care of this?

**Comment by 0xdevcollins** [comment]
I'd love to give this a go.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Stellar blockchain development and Rust programming. My skill set includes building decentralized applications, writing performant and safe code, and integrating blockchain systems.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!    

Looking forward to contributing!

**Comment by jaykayudo** [comment]
Can i be assigned this issue?
I am a full stack developer with ample experience in building innovative and scalable solutions. on the blockchain side, i bring expertise in DAPP development, smart contract design and integration of several chains technology.

### How i will tackle this
- I will follow the contribution guideline to the letter
-  I will create the page and the form based on the description
- I will open a PR within 2 days

**Comment by abdegenius** [comment]
I’d like to work on this.

**Comment by mimisavage** [comment]
I'd love to give this a go.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
@JoelVR17 
Please i am an experienced Frontend developer with 3 years of experience. Kindly assign this task to me. I will make PR in 2 days.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ikemHood** [comment]
I am Ikem Peter a software developer with 3+ years of expierence
I would love to tackle this issue,
I would create the Report form, and configure the firebase to save form data,
then add link to the report form
EDT: 24hrs

**Comment by 3th-Enjay** [comment]
Mind if I try this one?

**Comment by blessingbytes** [comment]
Pls, I’d love to work on this task.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will create the "Report an API Issue" page with a form that includes fields for Name, Last Name, Email, Type (Bug or Recommendation), and Description. The form will be validated to ensure all fields are required, and upon submission, the data will be stored in Firebase under the API issues collection. I'll add links to this page in the sidebar and homepage near the Connect/Disconnect button. The UI will follow consistent design standards, support both light and dark modes, and be fully responsive.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects)

**Comment by Kachimercy1** [comment]
Mind if I take this issue?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by brolag** [comment]
I'd like to work in this issue. I have more than 10 years of experience working with web technologies.

My plan is:

1) Create a input components if required.
2) Add validations (we may use zod and react hook form)
3) Integrate the form with Firebase.
4) Fix the UI to match the current design.
5) Test the integration.

I have contributed to several projects working on this kind of issues, here are some examples:

https://github.com/safetrustcr/Frontend/issues/68
https://github.com/Vagabonds-Labs/cofiblocks

**Comment by Amarjeet325** [comment]
Would love to tackle this!

**Comment by salazarsebas** [comment]
Hi Trustless Work,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Create the page with all the required fields.
- Make sure the UI looks very good.
- Make all fields mandatory.
- Direct the data to be stored in firebase and verify that it is done properly.
- Follow the design standards and any doubt evacuate it with the team.
- Make sure it is fully responsive.
- Perform all the tests and send the pr waiting for feedback.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by tamaraantonella** [comment]
Would love to tackle this!

**Comment by ShantelPeters** [comment]
Let me try this one!

**Comment by JoelVR17** [comment]
This issue is for you @tamaraantonella! 🚀
Remember to follow all the guidelines, both the ones inside the repository and the guideline to perform the PR.

Many thanks to all the other dev's who sent in their application.
